Zizaco/entrust

src/commands/MigrationCommand.php

- default to ‘Yes’ when you hit enter
- fix path to migrations for Laravel 5
- small spelling error

Fix up MigrationCommand

---

src/views/generators/migration.blade.php

I think it's good to reverse the migration in receding scenario, as reverse mean to last in first out (lifo)

Re-order reverse migration scenario to LIFO

---

src/Entrust/Contracts/EntrustUserInterface.php
src/Entrust/EntrustPermission.php
src/Entrust/EntrustRole.php
src/Entrust/EntrustServiceProvider.php
src/Entrust/Traits/EntrustUserTrait.php
src/config/config.php
tests/EntrustTest.php

Laravel 5 already requires PHP >=5.4, so we can use bracket syntax without hesitation. By the way it's already used in some places in this package.

Update array syntax

---

src/Entrust/EntrustServiceProvider.php
src/commands/ClassCreatorCommand.php
src/views/generators/class.blade.php

Created Artisan command `php artisan entrust:classes` that generates all requires classes (Role, Permission).
Copying classes from readme is a bit weird, so let's have a convenient way to automatically generate them.

Add artisan command to create models

---

src/Entrust/Traits/EntrustUserTrait.php

The roles were deleted because EntrustUserTrait was looking for the old name of the SoftDeletingTrait that was changed to SoftDeletes.

Reflect renaming of SoftDeletingTrait to SoftDeletes

---

README.md
src/Entrust/Traits/EntrustUserTrait.php
tests/EntrustUserTest.php

initial credit goes to @hkan for https://github.com/Zizaco/entrust/pull/234
I have updated the initial pull request with tests as well so hopefully this can be pulled in? @Zizaco 
"This is be useful for the people that namespace their permissions like me. With this PR, it will be possible to check permissions like $user->can('posts.*') to see if user has any permission under the posts namespace."

Placeholder Support to Permission Check (update of #234)

---

README.md
src/Entrust/Middleware/EntrustAbility.php
src/Entrust/Middleware/EntrustPermission.php
src/Entrust/Middleware/EntrustRole.php

Implemented middleware. Closes #316
We probably still need to inject and use `App::abort(403)` instead of `abort(403)` helper function. Also this feature still needs tests and I don't have experience writing them.
Functionality can be further enhanced by allowing user to return custom responses in case of failed authorization. One way is to add additional parameter to middleware as redirect URL but that will require to hardcode redirect response in middleware since middleware parameters are strings. Probably there are more flexible solutions.

Implement middleware

---

composer.json

Move test file to autoload-dev to fix composer update

---

README.md
src/Entrust/EntrustServiceProvider.php

With this new feature, 3 directives are available for use within your Blade templates. What you give as the directive arguments will be directly passed to the corresponding `Entrust` function.
```php
@role('admin')
<p>This is visible to users with the admin role. Gets translated to 
\Entrust::role('admin')</p>
@endrole
@permission('manage-admins')
<p>This is visible to users with the given permissions. Gets translated to 
\Entrust::can('manage-admins'). The @can directive is already taken by core 
laravel authorization package, hence the @permission directive instead.</p>
@endpermission
@ability('admin,owner', 'create-post,edit-user')
<p>This is visible to users with the given abilities. Gets translated to 
\Entrust::ability('admin,owner', 'create-post,edit-user')</p>
@endability
```

Blade support

---

src/Entrust/EntrustServiceProvider.php

Right now returns:
```
PHP Fatal error:  Class 'Zizaco\Entrust\Blade' not found in /private/var/www/bonappetour/vendor/zizaco/entrust/src/Entrust/EntrustServiceProvider.php on line 63
[Symfony\Component\Debug\Exception\FatalErrorException] Class 'Zizaco\Entrust\Blade' not found
```

Fix namespace

---

.travis.yml
composer.json
composer.lock
src/Entrust/Traits/EntrustRoleTrait.php
src/Entrust/Traits/EntrustUserTrait.php
tests/EntrustUserTest.php

Entrust permission caching

---

README.md
src/Entrust/Traits/EntrustRoleTrait.php
src/config/config.php

If the Model classes for Permission and Role are not named as such, trying to get all permission for a role will throw an error because eloquent constructs the foreign keys from the model class name.
The user relationship already uses a config option to get the foreign keys.

Permission foreign key

---

README.md

The Still Maintained domain seems to have expired on the 8th meaning users which do not have it cached cannot see the image.

Removed Still Maintained Image

---

src/Entrust/Entrust.php

Update Entrust.php for laravel-5-dev

Fix Call to undefined method Zizaco\Entrust\Entrust::ability() 5.1

---

src/commands/MigrationCommand.php

Solving Entrust migration issue with Laravel 5.2
`php artisan entrust:migration`
> [Symfony\Component\Debug\Exception\FatalErrorException]
> Class name must be a valid object or a string

Solving Issue: Class name must be a valid object or a string

---

README.md

Middleware route need backslash at the front, otherwise, middleware will not be registered.

Fix typo in README.md at middleware section

---

src/Entrust/Traits/EntrustRoleTrait.php

Fix save/delete/restore methods to return value as it designed in "Illuminate\Database\Eloquent\Model" and "Illuminate\Database\Eloquent\SoftDeletes"
This restore expected behavior of save/delete/restore methods in inherited classes

Fix EntrustRoleTrait

---

src/commands/MigrationCommand.php

When generating the Entrust migration, fall back to the default users table in case it's not defined.
Solves #544, #510, #462.
Cheers

Fall back to the default users table in case it's not defined

---

src/Entrust/Traits/EntrustRoleTrait.php
src/Entrust/Traits/EntrustUserTrait.php
tests/EntrustUserTest.php

Bypass cache when `file` or `database` cache drivers are set.
Solves #541, #537, #450, #422.

Bypass cache when file or database cache drivers are set

---

src/Entrust/Middleware/EntrustAbility.php
src/Entrust/Middleware/EntrustPermission.php
src/Entrust/Middleware/EntrustRole.php

This updates the middleware to handle the parameters accepted a
little better - includes only `explode`ing the values when needed
and also coercing items expected to be `bool` with `filter_var`
Fixes issues #575

Clean up Middleware parameter handling

---

src/Entrust/Traits/EntrustRoleTrait.php

Caching was being done but by default there is no config option for ttl causing it to expire instantly. This is just a default value that can be overwritten with a `cache.ttl` option.
This option should really be moved to Entrusts own config file. This fixes issue #537.

Added Default Cache Time

---

src/Entrust/EntrustServiceProvider.php

Lumen does not provide the `config_path()` helper by default, so use the manual version instead, since this is the only time Entrust uses config_path.
Also abort setting Blade directives if Blade is not available.

Make compatible with Lumen for #369.

---

src/commands/MigrationCommand.php
src/config/config.php

This error is thrown on Laravel 5.2. The user model path and users table are not defined in confg\auth.php so I added these to the entrust config file. when a user publishes entrust, they can edit this value if their user table or model is named different than laravel expects. 
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class name must be a valid object or a string

Fixed Config for Laravel 5.2 and later 

---

src/commands/MigrationCommand.php

The table name is not set as 'auth.providers.users.model' in atleast Laravel 5.2.41. But since we got the model anyway. Why no use ->getTable(); Tested & Working.

Fix for migration missing table name

---

src/Entrust/EntrustServiceProvider.php

For laravel 5.3 you need to put extra ( ) around $expression. It is mentioned in the upgrade guide.
Otherwise your blade directives doesnt work.
For laravel 5.2 this cannot be done, so maybe another branch for laravel 5.3?

brackets around expression for laravel 5.3

---

src/Entrust/EntrustServiceProvider.php

The **( )** are missing in all the blade directives.
Current code Example: 
@role('admin')    =>    <?php if (\Entrust::hasRole'admin') : ?>
After this fix Example:
@role('admin')    =>    <?php if (\Entrust::hasRole**(**'admin'**)**) : ?>

Update EntrustServiceProvider to fix Blade directives

---

src/Entrust/Traits/EntrustRoleTrait.php

Issue #352: Undefined index: id during attachPermission using array
Traits\EntrustRoleTrait:173 in attachPermission
When input is determined to be an array, the function incorrectly attempts
to get the value of the 'id' attribute instead of processing a list of
Roles.  Fix calls attachPermissions on $permission instead, giving the
desired functionality.
Traits\EntrustRoleTrait:192 in detachPermission
See above.
Refactors Traits\EntrustRoleTrait:detachPermission to follow coding standard

Fixes Issue #352

---

.travis.yml

> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
adds trusty distribution to travis config for hhvm build error.

adds trusty distribution to travis config
